management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
spring:
  cloud:
    gateway:
      routes:
      - id: checkin-service
        uri: http://checkin-service
        predicates:
        - Path=/api/**
        filters:
        - StripPrefix=1